services:
  postgres:
    container_name: postgres-sql
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book-store
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - book-store
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - book-store

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - book-store

networks:
  book-store:
    driver: bridge

volumes:
  postgres:
    driver: local
